CREATE TABLE IF NOT EXISTS `basitkargo` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `id_order` INT(11) NOT NULL,
  `cargo_code` VARCHAR(128) NOT NULL,
  `cargo` VARCHAR(128) NOT NULL,
  `date_add` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

