<?php
/**
 * One-off helper: build lang/admin/en.php + tr.php and patch admin templates.
 * Run: php tools/migrate-admin-lang.php
 */
$root = dirname(__DIR__);
$oldEn = require $root . '/lang/admin/en.php';
if (!is_array($oldEn)) {
	$oldEn = [];
}

$extraEn = [
	// Already English in templates
	'Templates' => 'Templates',
	'Add New' => 'Add New',
	'Search' => 'Search',
	'Search..' => 'Search..',
	'Active' => 'Active',
	'Upload zip file' => 'Upload zip file',
	'Copy Theme' => 'Copy Theme',
	'Theme Folder Name' => 'Theme Folder Name',
	'Theme Name' => 'Theme Name',
	'Zip File' => 'Zip File',
	'Ensure the files are complete.' => 'Ensure the files are complete.',
	'Save' => 'Save',
	'Yes' => 'Yes',
	'No' => 'No',
	'Detail' => 'Detail',
	'Order' => 'Order',
	'Customer' => 'Customer',
	'Date' => 'Date',
	'Status' => 'Status',
	'Tracking' => 'Tracking',
	'News' => 'News',
	'Performance' => 'Performance',
	'API Keys' => 'API Keys',
	'Shipping' => 'Shipping',
	'Coupons & Promotions' => 'Coupons & Promotions',
	'Cart Promotion' => 'Cart Promotion',
	'New Cart Promotion' => 'New Cart Promotion',
	'Promotion:' => 'Promotion:',
	'Return #' => 'Return #',
	'Cancel #' => 'Cancel #',
	'Return request not found' => 'Return request not found',
	'Cancel request not found' => 'Cancel request not found',
	'Order Messages' => 'Order Messages',
	'Order #' => 'Order #',
	'CMS:' => 'CMS:',
	// Settings page
	'General' => 'General',
	'Store currency' => 'Store currency',
	'Manage currencies' => 'Manage currencies',
	'Use the currencies page to add units or change the active currency.' => 'Use the currencies page to add units or change the active currency.',
	'Contact' => 'Contact',
	'If you use PHP mail(), this email is used as the sender address.' => 'If you use PHP mail(), this email is used as the sender address.',
	'Email delivery' => 'Email delivery',
	'PHP mail() - Server mail system' => 'PHP mail() - Server mail system',
	'SMTP - External mail server' => 'SMTP - External mail server',
	'SMTP configuration is ready.' => 'SMTP configuration is ready.',
	'Sender email is set for PHP mail().' => 'Sender email is set for PHP mail().',
	'Complete SMTP settings (host, user, password).' => 'Complete SMTP settings (host, user, password).',
	'Enter a contact email for PHP mail().' => 'Enter a contact email for PHP mail().',
	'Leave blank to keep the current password.' => 'Leave blank to keep the current password.',
	'None' => 'None',
	'Site name' => 'Site name',
	'On local stacks like WAMP/XAMPP, PHP mail() usually fails. Use production hosting or SMTP.' => 'On local stacks like WAMP/XAMPP, PHP mail() usually fails. Use production hosting or SMTP.',
	'Order number' => 'Order number',
	'Store, POS and online orders use the same numbering rule. Set a prefix (ECZ, EST, etc.) to distinguish sites.' => 'Store, POS and online orders use the same numbering rule. Set a prefix (ECZ, EST, etc.) to distinguish sites.',
	'e.g. ECZ, EST' => 'e.g. ECZ, EST',
	'Optional. Letters and digits only.' => 'Optional. Letters and digits only.',
	'Example:' => 'Example:',
	'The next order number will look like this.' => 'The next order number will look like this.',
	'Returns' => 'Returns',
	'Customers can open return requests only for <strong>delivered</strong> orders within this many days after delivery. 0 = disabled.' => 'Customers can open return requests only for <strong>delivered</strong> orders within this many days after delivery. 0 = disabled.',
	'Test email address' => 'Test email address',
	'Send test email' => 'Send test email',
	'Read only' => 'Read only',
	'Folder:' => 'Folder:',
	'Domain and folder must be changed directly in the database.' => 'Domain and folder must be changed directly in the database.',
	'Web API' => 'Web API',
	'Partner API keys and permissions are managed on a separate page.' => 'Partner API keys and permissions are managed on a separate page.',
	'Go to API settings' => 'Go to API settings',
	'Email info' => 'Email info',
	'Hosting server mail() function' => 'Hosting server mail() function',
	'External server such as frisay.com' => 'External server such as frisay.com',
	'Test errors are now shown in detail' => 'Test errors are now shown in detail',
	'SSL usually uses port 465' => 'SSL usually uses port 465',
	// Settings keys (config.php)
	'Site name' => 'Site name',
	'Contact email' => 'Contact email',
	'Phone (display)' => 'Phone (display)',
	'Phone (tel link)' => 'Phone (tel link)',
	'Return request window (days)' => 'Return request window (days)',
	'Order number prefix' => 'Order number prefix',
	'Order number format' => 'Order number format',
	'Sequential digit count' => 'Sequential digit count',
	'Mail driver' => 'Mail driver',
	'SMTP host' => 'SMTP host',
	'SMTP port' => 'SMTP port',
	'SMTP user (email)' => 'SMTP user (email)',
	'SMTP password' => 'SMTP password',
	'Encryption (ssl / tls)' => 'Encryption (ssl / tls)',
	'From email' => 'From email',
	'From name (empty = site name)' => 'From name (empty = site name)',
	// Order ref modes
	'Sequential number (00123)' => 'Sequential number (00123)',
	'Unix timestamp (time)' => 'Unix timestamp (time)',
	'Date and time (YmdHis)' => 'Date and time (YmdHis)',
	'Random code' => 'Random code',
	'Date + random (ymd + code)' => 'Date + random (ymd + code)',
	// Flash / PHP messages
	'Settings saved' => 'Settings saved',
	'Some settings could not be saved' => 'Some settings could not be saved',
	'Enter a valid email address for the test' => 'Enter a valid email address for the test',
	'Test email sent' => 'Test email sent',
	'Test email could not be sent' => 'Test email could not be sent',
	'Complete SMTP settings. Enter server, user and password.' => 'Complete SMTP settings. Enter server, user and password.',
	'Enter contact or sender email for PHP mail().' => 'Enter contact or sender email for PHP mail().',
	'Web API management moved: Admin → API menu' => 'Web API management moved: Admin → API menu',
	// Footer modal
	'Confirm action' => 'Confirm action',
	'Are you sure you want to perform this action?' => 'Are you sure you want to perform this action?',
	'Close' => 'Close',
	'Yes, confirm' => 'Yes, confirm',
	'% vs yesterday' => '% vs yesterday',
	'Reviews awaiting approval.' => 'Reviews awaiting approval.',
	'News feed could not be loaded.' => 'News feed could not be loaded.',
	'Order information' => 'Order information',
	'Back to orders' => 'Back to orders',
	'Store themes' => 'Store themes',
	'Module store' => 'Module store',
	'Notifications' => 'Notifications',
	'Languages' => 'Languages',
	'Currencies' => 'Currencies',
	'Pages' => 'Pages',
	'Categories' => 'Categories',
	'Brands' => 'Brands',
	'Customers' => 'Customers',
	'Messages' => 'Messages',
	'Coupons' => 'Coupons',
	'Modules' => 'Modules',
	'Settings' => 'Settings',
	'Site settings' => 'Site settings',
];

$en = [];
$tr = [];

foreach ($oldEn as $turkishKey => $englishValue) {
	$englishValue = (string) $englishValue;
	$en[$englishValue] = $englishValue;
	$tr[$englishValue] = (string) $turkishKey;
}

foreach ($extraEn as $key => $value) {
	$en[$key] = $value;
	if (!isset($tr[$key])) {
		$tr[$key] = $key; // fallback until translated
	}
}

// Turkish translations for extra keys
$trExtras = [
	'Templates' => 'Temalar',
	'Add New' => 'Yeni Ekle',
	'Search' => 'Ara',
	'Search..' => 'Ara..',
	'Active' => 'Aktif',
	'Upload zip file' => 'Zip dosyası yükle',
	'Copy Theme' => 'Temayı kopyala',
	'Theme Folder Name' => 'Tema klasör adı',
	'Theme Name' => 'Tema adı',
	'Zip File' => 'Zip dosyası',
	'Ensure the files are complete.' => 'Dosyaların eksiksiz olduğundan emin olun.',
	'Save' => 'Kaydet',
	'Yes' => 'Evet',
	'No' => 'Hayır',
	'Detail' => 'Detay',
	'Order' => 'Sipariş',
	'Customer' => 'Müşteri',
	'Date' => 'Tarih',
	'Status' => 'Durum',
	'Tracking' => 'Takip',
	'News' => 'Haberler',
	'Performance' => 'Performans',
	'API Keys' => 'API Anahtarları',
	'Shipping' => 'Kargolar',
	'Coupons & Promotions' => 'Kuponlar & Kampanyalar',
	'Cart Promotion' => 'Sepet Kampanyası',
	'New Cart Promotion' => 'Yeni Sepet Kampanyası',
	'Promotion:' => 'Kampanya:',
	'Return #' => 'İade #',
	'Cancel #' => 'İptal #',
	'Return request not found' => 'İade Talebi Bulunamadı',
	'Cancel request not found' => 'İptal Talebi Bulunamadı',
	'Order Messages' => 'Sipariş Mesajları',
	'Order #' => 'Sipariş #',
	'CMS:' => 'CMS:',
	'General' => 'Genel',
	'Store currency' => 'Mağaza para birimi',
	'Manage currencies' => 'Para birimlerini yönet',
	'Use the currencies page to add units or change the active currency.' => 'Yeni birim eklemek veya aktif birimi değiştirmek için para birimleri sayfasını kullanın.',
	'Contact' => 'İletişim',
	'If you use PHP mail(), this email is used as the sender address.' => 'PHP mail() kullanıyorsanız gönderen adres olarak bu e-posta kullanılır.',
	'Email delivery' => 'E-posta Gönderimi',
	'PHP mail() - Server mail system' => 'PHP mail() - Sunucunun kendi mail sistemi',
	'SMTP - External mail server' => 'SMTP - Harici mail sunucusu',
	'SMTP configuration is ready.' => 'SMTP yapılandırması hazır.',
	'Sender email is set for PHP mail().' => 'PHP mail() için gönderen e-posta tanımlı.',
	'Complete SMTP settings (host, user, password).' => 'SMTP ayarlarını tamamlayın (sunucu, kullanıcı, şifre).',
	'Enter a contact email for PHP mail().' => 'PHP mail() için İletişim e-postası girin.',
	'Leave blank to keep the current password.' => 'Boş bırakırsanız mevcut şifre korunur.',
	'None' => 'Yok',
	'Site name' => 'Site Adı',
	'On local stacks like WAMP/XAMPP, PHP mail() usually fails. Use production hosting or SMTP.' => 'WAMP/XAMPP gibi yerel ortamlarda PHP mail() genelde çalışmaz. Canlı sunucuda veya SMTP ile deneyin.',
	'Order number' => 'Sipariş Numarası',
	'Store, POS and online orders use the same numbering rule. Set a prefix (ECZ, EST, etc.) to distinguish sites.' => 'Mağaza, POS ve online siparişler aynı numara kuralını kullanır. Farklı siteler için önek (ECZ, EST vb.) tanımlayabilirsiniz.',
	'e.g. ECZ, EST' => 'ör. ECZ, EST',
	'Optional. Letters and digits only.' => 'Boş bırakılabilir. Yalnızca harf ve rakam.',
	'Example:' => 'Örnek:',
	'The next order number will look like this.' => 'Bir sonraki sipariş numarası buna benzer olur.',
	'Returns' => 'İade',
	'Customers can open return requests only for <strong>delivered</strong> orders within this many days after delivery. 0 = disabled.' => 'Müşteriler yalnızca <strong>teslim edilmiş</strong> siparişler için, teslim tarihinden itibaren bu gün sayısı içinde iade talebi oluşturabilir. 0 = kapalı.',
	'Test email address' => 'Test e-posta adresi',
	'Send test email' => 'Test Maili Gönder',
	'Read only' => 'Salt Okunur',
	'Folder:' => 'Klasör:',
	'Domain and folder must be changed directly in the database.' => 'Domain ve klasör ayarları veritabanından doğrudan değiştirilmelidir.',
	'Web API' => 'Web API',
	'Partner API keys and permissions are managed on a separate page.' => 'Partner API anahtarları ve yetkiler ayrı sayfada yönetilir.',
	'Go to API settings' => 'API Ayarlarına Git',
	'Email info' => 'E-posta Bilgisi',
	'Hosting server mail() function' => 'Hosting sunucusunun mail() fonksiyonu',
	'External server such as frisay.com' => 'frisay.com gibi harici sunucu',
	'Test errors are now shown in detail' => 'Test hatası artık detaylı gösterilir',
	'SSL usually uses port 465' => 'SSL için genelde port 465 kullanılır',
	'Contact email' => 'İletişim E-posta',
	'Phone (display)' => 'Telefon (görünen)',
	'Phone (tel link)' => 'Telefon (tel: linki)',
	'Return request window (days)' => 'İade talebi süresi (gün)',
	'Order number prefix' => 'Sipariş no öneki (prefix)',
	'Order number format' => 'Sipariş no formatı',
	'Sequential digit count' => 'Sıralı numara basamak sayısı',
	'Mail driver' => 'E-posta gönderim yöntemi',
	'SMTP host' => 'SMTP Sunucu',
	'SMTP port' => 'SMTP Port',
	'SMTP user (email)' => 'SMTP Kullanıcı (e-posta)',
	'SMTP password' => 'SMTP Şifre',
	'Encryption (ssl / tls)' => 'Şifreleme (ssl / tls)',
	'From email' => 'Gönderen e-posta',
	'From name (empty = site name)' => 'Gönderen adı (boş = site adı)',
	'Sequential number (00123)' => 'Sıralı numara (00123)',
	'Unix timestamp (time)' => 'Unix zaman damgası (time)',
	'Date and time (YmdHis)' => 'Tarih + saat (YmdHis)',
	'Random code' => 'Rastgele kod',
	'Date + random (ymd + code)' => 'Tarih + rastgele (ymd + kod)',
	'Settings saved' => 'Ayarlar kaydedildi',
	'Some settings could not be saved' => 'Bazı ayarlar kaydedilemedi',
	'Enter a valid email address for the test' => 'Test için geçerli bir e-posta adresi girin',
	'Test email sent' => 'Test maili gönderildi',
	'Test email could not be sent' => 'Test maili gönderilemedi',
	'Complete SMTP settings. Enter server, user and password.' => 'SMTP ayarları eksik. Sunucu, kullanıcı ve şifre girin.',
	'Enter contact or sender email for PHP mail().' => 'PHP mail() için İletişim e-postası veya gönderen e-posta girin.',
	'Web API management moved: Admin → API menu' => 'Web API yönetimi taşındı: Admin → API menüsü',
	'Confirm action' => 'İşlem Onayı',
	'Are you sure you want to perform this action?' => 'Bu işlemi gerçekleştirmek istediğinize emin misiniz?',
	'Close' => 'Kapat',
	'Yes, confirm' => 'Evet, Onayla',
	'% vs yesterday' => '% dünle kıyasla',
	'Reviews awaiting approval.' => 'yorum onay bekliyor.',
	'News feed could not be loaded.' => 'Haber beslemesi yüklenemedi.',
	'Order information' => 'Sipariş Bilgileri',
	'Back to orders' => 'Sipariş listesine dön',
	'Store themes' => 'Temalar',
	'Module store' => 'Eklenti Mağazası',
	'Notifications' => 'Bildirimler',
	'Languages' => 'Diller',
	'Currencies' => 'Para Birimleri',
	'Pages' => 'Sayfalar',
	'Categories' => 'Kategoriler',
	'Brands' => 'Markalar',
	'Customers' => 'Müşteriler',
	'Messages' => 'Mesajlar',
	'Coupons' => 'Kuponlar',
	'Modules' => 'Modüller',
	'Settings' => 'Ayarlar',
	'Site settings' => 'Site Ayarları',
	'Order no' => 'Sipariş no',
	'Customer name' => 'Müşteri adı',
	'Order status' => 'Sipariş durumu',
	'All statuses' => 'Tüm durumlar',
	'Start date' => 'Başlangıç tarihi',
	'End date' => 'Bitiş tarihi',
	'Filter' => 'Filtrele',
	'Clear' => 'Temizle',
	'Full name' => 'Ad soyad',
	'Last 50 Orders' => 'Son 50 Sipariş',
	'View all' => 'Tümünü gör',
	'Invalid request' => 'Geçersiz istek',
	'Details' => 'Detaylar',
	'Delete' => 'Sil',
	'Cancel' => 'İptal',
	'Search...' => 'Ara...',
	'Admin panel language' => 'Admin panel dili',
	'Admin interface language. Switch instantly from the header; set the default here.' => 'Yönetim paneli arayüz dili. Üst bardaki dil seçici ile anlık değiştirilebilir; buradan varsayılan ayarlanır.',
	'Default admin language' => 'Varsayılan admin dili',
	'Active languages' => 'Aktif diller',
	'Cancellations' => 'İptaller',
	'Message details' => 'Mesaj Detayı',
	'Contact messages' => 'İletişim Mesajları',
	'SEO settings' => 'SEO Ayarları',
	'New product' => 'Yeni Ürün',
	'Edit product' => 'Ürün Düzenle',
	'New category' => 'Yeni Kategori',
	'Edit category' => 'Kategori Düzenle',
	'New brand' => 'Yeni Marka',
	'Edit brand' => 'Marka Düzenle',
	'New coupon' => 'Yeni Kupon',
	'New CMS page' => 'Yeni CMS Sayfası',
	'Page not found' => 'Sayfa Bulunamadı',
	'Product not found' => 'Ürün Bulunamadı',
	'Order not found' => 'Sipariş Bulunamadı',
	'Customer not found' => 'Müşteri Bulunamadı',
	'Message not found' => 'Mesaj Bulunamadı',
	'Coupon not found' => 'Kupon Bulunamadı',
	'Brand not found' => 'Marka Bulunamadı',
	'Category not found' => 'Kategori Bulunamadı',
	'Module not found' => 'Modül Bulunamadı',
	'Admin login' => 'Admin Giriş',
	'Welcome' => 'Hoş geldiniz',
	'Sign in to the admin panel' => 'Yönetim paneline giriş yapın',
	'Email' => 'E-posta',
	'Password' => 'Şifre',
	'Sign in' => 'Giriş Yap',
	'← Back to store' => '← Mağazaya dön',
	'Manage your store from one place — orders, products and customers at your fingertips.' => 'Mağazanızı tek panelden yönetin — siparişler, ürünler ve müşteriler elinizin altında.',
	'Dashboard' => 'Gösterge Paneli',
	'Orders' => 'Siparişler',
	'View store' => 'Mağazayı Gör',
	'View site' => 'Siteyi Gör',
	'Track store performance and recent orders here.' => 'Mağaza performansınızı ve güncel siparişleri buradan takip edin.',
	'Today revenue' => 'Bugünkü Ciro',
	'Yesterday:' => 'Dün:',
	'Last 30 days revenue' => 'Son 30 Gün Ciro',
	'Total:' => 'Toplam:',
	'Today orders' => 'Bugünkü Sipariş',
	'orders' => 'sipariş',
	'Pending actions' => 'Bekleyen İşlem',
	'Approval + processing' => 'Onay + hazırlık aşaması',
	'Active products' => 'Aktif Ürün',
	'low stock' => 'düşük stok',
	'Registered customers' => 'Kayıtlı Müşteri',
	'today' => 'bugün',
	'Unread messages' => 'Okunmamış Mesaj',
	'Total orders' => 'Toplam Sipariş',
	'Daily sales trend' => 'Günlük Satış Trendi',
	'days' => 'gün',
	'Operations (7 days)' => 'Operasyon (7 gün)',
	'Awaiting approval' => 'Onay Bekliyor',
	'Processing' => 'Hazırlanıyor',
	'Shipped' => 'Kargoda',
	'Awaiting shipment' => 'Kargo bekleyen',
	'Recent orders' => 'Son Siparişler',
	'No orders yet.' => 'Henüz sipariş yok.',
	'Top selling products' => 'Çok Satan Ürünler',
	'sold' => 'adet satıldı',
	'No sales data yet.' => 'Henüz satış verisi yok.',
	'All' => 'Tümü',
	'No records found.' => 'Kayıt bulunamadı.',
	'View' => 'Görüntüle',
	'Print' => 'Yazdır',
	'Catalog' => 'Katalog',
	'System' => 'Sistem',
	'Modules' => 'Modüller',
	'Module store' => 'Eklenti Mağazası',
	'Admin panel' => 'Yönetim Paneli',
	'Search products...' => 'Ürün ara...',
	'Quick access' => 'Hızlı erişim',
	'Sign out' => 'Çıkış Yap',
	'Language' => 'Dil',
	'New Product' => 'Yeni Ürün',
	'Welcome back' => 'Hoş geldin',
];
$tr = array_merge($tr, $trExtras);

ksort($en);
ksort($tr);

$writeLang = static function (string $path, array $data): void {
	$lines = ["<?php", "\treturn ["];
	foreach ($data as $k => $v) {
		$lines[] = "\t\t" . var_export($k, true) . ' => ' . var_export($v, true) . ',';
	}
	$lines[] = "\t];";
	file_put_contents($path, implode("\n", $lines) . "\n");
};

$writeLang($root . '/lang/admin/en.php', $en);
$writeLang($root . '/lang/admin/tr.php', $tr);

// Patch templates: Turkish adminT keys -> English
$dirs = [$root . '/templates/admin'];
$replaceCount = 0;
foreach ($oldEn as $turkishKey => $englishValue) {
	$from = "{'{$turkishKey}'|adminT}";
	$to = "{'{$englishValue}'|adminT}";
	foreach ($dirs as $dir) {
		$it = new RecursiveIteratorIterator(new RecursiveDirectoryIterator($dir));
		foreach ($it as $file) {
			if ($file->getExtension() !== 'tpl') {
				continue;
			}
			$path = $file->getPathname();
			$content = file_get_contents($path);
			if (strpos($content, $from) === false) {
				continue;
			}
			$new = str_replace($from, $to, $content, $count);
			if ($count > 0) {
				file_put_contents($path, $new);
				$replaceCount += $count;
			}
		}
	}
}

echo "Wrote en.php (" . count($en) . " keys), tr.php (" . count($tr) . " keys), template replacements: {$replaceCount}\n";
